### ISSUE TITLE
How to control order of projects listing

### ISSUE THREAD

**Issue by Qyoom** [commonplaceworld/udacity-hugo-theme#8]
It seems that, similar to blog posts, the projects list on the main page are ordered by date, newest to oldest. Is there a way we can control that order differently, so that we can choose our own order of importance?

**Comment by ammarasmro** [comment]
There are several ways to control the order. The details are here [Hugo Documentation](https://gohugo.io/templates/lists/)
I feel that we should use the sort by weight, which allows us to give each project weight value in the front matter, any integer over zero works. I just tested it for the projects and it worked, let me know if you like it so that I can set it up.

Here is an example of the flipped articles in the project section
<img width="448" alt="screen shot 2018-06-26 at 7 09 31 pm" src="https://user-images.githubusercontent.com/22536934/41947391-8b70b01c-7974-11e8-90cb-80ff44c41732.png">
<img width="827" alt="screen shot 2018-06-26 at 7 09 24 pm" src="https://user-images.githubusercontent.com/22536934/41947392-8b89093c-7974-11e8-9972-8de198a506c1.png">

**Comment by Qyoom** [comment]
I like it! Simple enough, big help, thx!
